version: '2'
services:
  freenet:
    container_name: freenet
    image: infincia/docker-freenet:master
    network_mode: "host"
    ports:
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:9481:9481"
    volumes:
      - /conf/freenet:/conf
      - /data/freenet:/data
    environment:
    - allowedhosts=127.0.0.1,0:0:0:0:0:0:0:1
