#!/bin/sh

if [ ! -f /conf/freenet.ini ]; then
    cp /defaults/freenet.ini /conf/
fi

cd /fred

exec java -Xms60M -Xss384K -Xmx384M -cp freenet-ext.jar:freenet-stable-latest.jar:bcprov-jdk15on-154.jar freenet.node.NodeStarter /conf/freenet.ini
